# Generated by Django 3.2.9 on 2022-02-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.CharField(max_length=100)),
                ('psswrd', models.CharField(max_length=100)),
                ('psswrd_re', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('phno', models.BigIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Lform',
            new_name='Lforms',
        ),
    ]
